# Generated by Django 5.2 on 2025-04-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
